// Dữ liệu kệ đã xuất
const exportedData = [
    { "npp": "NPP Vũ Tấm", "sl": 480 },
    { "npp": "NPP Dũng Cúc", "sl": 36 },
    { "npp": "NPP Công Giang", "sl": 102 },
    { "npp": "NPP Thảo Nam", "sl": 170 },
    { "npp": "NPP Tuấn Yến", "sl": 134 },
    { "npp": "NPP Bảo Lâm", "sl": 281 },
    { "npp": "NPP Nguyên Vũ", "sl": 162 },
    { "npp": "NPP Tuấn Huê", "sl": 146 },
    { "npp": "NPP Long Liên", "sl": 191 },
    { "npp": "NPP Cường Thịnh", "sl": 87 },
    { "npp": "NPP Đức Nam Tiến", "sl": 137 },
    { "npp": "NPP Lâm Hạ", "sl": 142 },
    { "npp": "NPP Thành Lụa", "sl": 118 },
    { "npp": "NPP Phương Đông", "sl": 473 },
    { "npp": "NPP Tuấn Huyền", "sl": 155 },
    { "npp": "NPP Hùng Huệ", "sl": 156 },
    { "npp": "NPP Ngọc Thêu", "sl": 177 },
    { "npp": "NPP Hoa Việt", "sl": 128 },
    { "npp": "NPP Phúc Thịnh", "sl": 40 },
    { "npp": "NPP Duy Anh", "sl": 106 },
    { "npp": "NPP Ngọc Kiên", "sl": 132 },
    { "npp": "NPP Phong Hiền", "sl": 86 },
    { "npp": "NPP Long Châm", "sl": 132 },
    { "npp": "NPP Thành Hân", "sl": 256 },
    { "npp": "NPP Long Hải", "sl": 231 },
    { "npp": "NPP Hikoji", "sl": 160 },
    { "npp": "NPP Bảo Cường", "sl": 221 },
    { "npp": "NPP Thắng Lợi", "sl": 259 },
    { "npp": "NPP Tân Hoa", "sl": 177 },
    { "npp": "NPP Tây Đô", "sl": 155 },
    { "npp": "NPP Tiến Thịnh", "sl": 199 },
    { "npp": "NPP Dương Minh", "sl": 205 },
    { "npp": "NPP Ánh Thu", "sl": 251 },
    { "npp": "NPP Đức Oanh", "sl": 162 },
    { "npp": "NPP Tùng Phương", "sl": 104 },
    { "npp": "NPP Thảo Thắng", "sl": 211 },
    { "npp": "NPP Hưng Thịnh", "sl": 192 },
    { "npp": "NPP Ngọc Phúc", "sl": 161 },
    { "npp": "NPP Nguyễn Đình Hân", "sl": 196 },
    { "npp": "NPP Tân Thúy", "sl": 341 },
    { "npp": "NPP Dũng Béo", "sl": 354 },
    { "npp": "NPP Thăng Hương", "sl": 50 },
    { "npp": "NPP Đồng Lợi", "sl": 260 },
    { "npp": "NPP Hoàng Minh", "sl": 290 },
    { "npp": "NPP Tuấn Vân", "sl": 63 },
    { "npp": "NPP Thái Hoà", "sl": 191 },
    { "npp": "NPP Duy Khoa", "sl": 183 },
    { "npp": "NPP Hiền Cường", "sl": 141 },
    { "npp": "NPP Oanh Định", "sl": 51 },
    { "npp": "NPP Thảo Xuân", "sl": 71 },
    { "npp": "NPP Vũ Đức Nam", "sl": 17 },
    { "npp": "NPP Hải Hằng", "sl": 170 },
    { "npp": "NPP Sơn Lâm", "sl": 248 },
    { "npp": "NPP Anh Minh HT", "sl": 206 },
    { "npp": "NPP Hồng Đức", "sl": 64 },
    { "npp": "NPP Minh Châu", "sl": 202 },
    { "npp": "NPP Mạnh Hà 1", "sl": 332 },
    { "npp": "NPP Mạnh Hà 2", "sl": 71 },
    { "npp": "NPP Nhung Tùng", "sl": 335 },
    { "npp": "NPP Thông Thơm", "sl": 68 },
    { "npp": "NPP Tân Bích An", "sl": 47 },
    { "npp": "NPP Linh Trang", "sl": 230 },
    { "npp": "NPP Minh Lộc", "sl": 70 },
    { "npp": "NPP Thanh Bình", "sl": 61 },
    { "npp": "NPP Thành Thanh", "sl": 89 },
    { "npp": "NPP Phương Hà", "sl": 144 },
    { "npp": "NPP Hà Thanh", "sl": 146 },
    { "npp": "NPP Trường Hằng", "sl": 56 },
    { "npp": "NPP Ánh Thu", "sl": 100, "ngay": "02/03/2026" },
    { "npp": "NPP Thái Hoà", "sl": 100, "ngay": "02/03/2026" },
    { "npp": "NPP Tân Thúy", "sl": 200, "ngay": "2/3/2026" },
    { "npp": "NPP Tuấn Yến", "sl": 150, "ngay": "02/03/2026" },
    { "npp": "NPP Tây Đô", "sl": 70, "ngay": "02/03/2026" },
    { "npp": "NPP Thanh Bình", "sl": 140, "ngay": "3/3/2026" },
    { "npp": "NPP Thành Lụa", "sl": 40, "ngay": "03/03/2026" },
    { "npp": "NPP Đức Nam Tiến", "sl": 120, "ngay": "03/03/2026" },
    { "npp": "NPP Tuấn Huê", "sl": 100, "ngay": "03/03/2026" },
    { "npp": "NPP Oanh Định", "sl": 150, "ngay": "3/3/2026" },
    { "npp": "NPP Bảo Cường", "sl": 72, "ngay": "03/03/2026" },
    { "npp": "NPP Phúc Thịnh", "sl": 100, "ngay": "03/03/2026" },
    { "npp": "NPP Hoàng Minh", "sl": 100, "ngay": "03/03/2026" },
    { "npp": "NPP Hiền Cường", "sl": 100, "ngay": "4/3/2026" },
    { "npp": "NPP Dương Minh", "sl": 150, "ngay": "6/3/2026" },
    { "npp": "NPP Trường Hằng", "sl": 120, "ngay": "7/3/2026" },
    { "npp": "NPP Hải Hằng", "sl": 100, "ngay": "09/03/2026" },
    { "npp": "NPP Duy Khoa", "sl": 180, "ngay": "10/3/2026" },
    { "npp": "NPP Nguyễn Đình Hân", "sl": 50, "ngay": "10/03/2026" },
    { "npp": "NPP Dũng Béo", "sl": 100, "ngay": "11/03/2026" },
    { "npp": "NPP Đức Oanh", "sl": 150, "ngay": "11/03/2026" },
    { "npp": "NPP Thành Thanh", "sl": 250, "ngay": "11/3/2026" },
    { "npp": "NPP Tuấn Huyền", "sl": 50, "ngay": "11/3/2026" },
    { "npp": "NPP Thảo Thắng", "sl": 100, "ngay": "11/3/2026" },
    { "npp": "NPP Thảo Xuân", "sl": 75, "ngay": "12/03/2026" },
    { "npp": "NPP Vũ Đức Nam", "sl": 50, "ngay": "12/03/2026" },
    { "npp": "NPP Hưng Thịnh", "sl": 125, "ngay": "12/3/2026" },
    { "npp": "NPP Tuấn Vân", "sl": 179, "ngay": "12/03/2026" },
    { "npp": "NPP Hùng Huệ", "sl": 50, "ngay": "12/3/2026" },
    { "npp": "NPP Tân Hoa", "sl": 80, "ngay": "12/3/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 100, "ngay": "13/03/2026" },
    { "npp": "NPP Thảo Nam", "sl": 100, "ngay": "13/03/2026" },
    { "npp": "NPP Duy Anh", "sl": 150, "ngay": "14/03/2026" },
    { "npp": "NPP Trường Hằng", "sl": 120, "ngay": "16/03/2026" },
    { "npp": "NPP Ngọc Phúc", "sl": 20, "ngay": "16/03/2026" },
    { "npp": "NPP Hà Thanh", "sl": 200, "ngay": "16/3/2026" },
    { "npp": "NPP Minh Lộc", "sl": 62, "ngay": "16/3/2026" },
    { "npp": "NPP Dũng Cúc", "sl": 50, "ngay": "18/03/2026" },
    { "npp": "NPP Phương Hà", "sl": 175, "ngay": "19/03/2026" },
    { "npp": "NPP Long Hải", "sl": 50, "ngay": "19/3/2026" },
    { "npp": "NPP Nguyên Vũ", "sl": 150, "ngay": "20/03/2026" },
    { "npp": "NPP Thái Hoà", "sl": 50, "ngay": "20/3/2026" },
    { "npp": "NPP Hoa Việt", "sl": 100, "ngay": "20/3/2026" },
    { "npp": "NPP Công Giang", "sl": 120, "ngay": "20/03/2026" },
    { "npp": "NPP Tiến Thịnh", "sl": 50, "ngay": "20/03/2026" },
    { "npp": "NPP Thành Hân", "sl": 50, "ngay": "21/03/2026" },
    { "npp": "NPP Vũ Đức Nam", "sl": 50, "ngay": "21/3/2026" },
    { "npp": "NPP Thảo Xuân", "sl": 100, "ngay": "21/03/2026" },
    { "npp": "NPP Sơn Lâm", "sl": 150, "ngay": "21/3/2026" },
    { "npp": "NPP Minh Lộc", "sl": 38, "ngay": "21/03/2026" },
    { "npp": "NPP Ngọc Kiên", "sl": 120, "ngay": "21/03/2026" },
    { "npp": " HT HT", "sl": 50, "ngay": "21/3/2026" },
    { "npp": "NPP Thảo Nam", "sl": 50, "ngay": "22/3/2026" },
    { "npp": "NPP Tân Hoa", "sl": 60, "ngay": "22/03/2026" },
    { "npp": "NPP Nguyễn Đình Hân", "sl": 100, "ngay": "22/03/2026" },
    { "npp": "NPP Vũ Tấm", "sl": 100, "ngay": "22/03/2026" },
    { "npp": "NPP Hikoji", "sl": 125, "ngay": "22/03/2026" },
    { "npp": "NPP Thăng Hương", "sl": 200, "ngay": "22/3/2026" },
    { "npp": "NPP Ngọc Phúc", "sl": 105, "ngay": "22/03/2026" },
    { "npp": "NPP Bảo Cường", "sl": 28, "ngay": "22/03/2026" },
    { "npp": "NPP Tiến Thịnh", "sl": 50, "ngay": "22/03/2026" },
    { "npp": "NPP Lâm Hạ", "sl": 200, "ngay": "22/03/2026" },
    { "npp": "NPP Phúc Thịnh", "sl": 50, "ngay": "23/3/2026" },
    { "npp": "NPP Phong Hiền", "sl": 150, "ngay": "23/03/2026" },
    { "npp": "NPP Tuấn Huê", "sl": 50, "ngay": "23/03/2026" },
    { "npp": "NPP Long Liên", "sl": 50, "ngay": "23/03/2026" },
    { "npp": "NPP Tân Bích An", "sl": 20, "ngay": "24/03/2026" },
    { "npp": "NPP Thông Thơm", "sl": 50, "ngay": "24/3/2026" },
    { "npp": "NPP Hồng Đức", "sl": 100, "ngay": "24/03/2026" },
    { "npp": "NPP Hồng Đức", "sl": 80, "ngay": "26/03/2026" },
    { "npp": "NPP Long Liên", "sl": 50, "ngay": "27/03/2026" },
    { "npp": "NPP Tuấn Huê", "sl": 100, "ngay": "27/03/2026" },
    { "npp": "NPP Tân Hoa", "sl": 10, "ngay": "27/03/2026" },
    { "npp": "NPP Thành Hân", "sl": 50, "ngay": "28/3/2026" },
    { "npp": "NPP Mạnh Hà 2", "sl": 50, "ngay": "28/03/2026" },
    { "npp": "NPP Anh Minh HT", "sl": 70, "ngay": "28/03/2026" },
    { "npp": "NPP Thông Thơm", "sl": 70, "ngay": "31/03/2026" },
    { "npp": "NPP Tùng Phương", "sl": 50, "ngay": "31/3/2026" },
    { "npp": "NPP Mạnh Hà 2", "sl": 50, "ngay": "1/4/2026" },
    { "npp": "NPP Phương Đông", "sl": 100, "ngay": "01/04/2026" },
    { "npp": "NPP Tân Bích An", "sl": 100, "ngay": "06/04/2026" },
    { "npp": "NPP Bảo Cường", "sl": 50, "ngay": "06/04/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 50, "ngay": "07/04/2026" },
    { "npp": "NPP Phúc Thịnh", "sl": 110, "ngay": "10/04/2026" },
    { "npp": "NPP Tây Đô", "sl": 50, "ngay": "10/04/2026" },
    { "npp": "NPP Vũ Tấm", "sl": 50, "ngay": "11/04/2026" },
    { "npp": "NPP Ánh Thu", "sl": 100, "ngay": "13/04/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 20, "ngay": "14/04/2026" },
    { "npp": "NPP Hikoji", "sl": 50, "ngay": "14/04/2026" },
    { "npp": "NPP Hưng Thịnh", "sl": 100, "ngay": "15/04/2026" },
    { "npp": "NPP Dương Minh", "sl": 100, "ngay": "16/04/2026" },
    { "npp": "NPP Ngọc Phúc", "sl": 100, "ngay": "16/04/2026" },
    { "npp": "NPP Nguyễn Đình Hân", "sl": 100, "ngay": "20/04/2026" },
    { "npp": "NPP Tuấn Huyền", "sl": 30, "ngay": "20/04/2026" },
    { "npp": "NPP Thái Hoà", "sl": 60, "ngay": "21/04/2026" },
    { "npp": "NPP Phương Đông", "sl": 100, "ngay": "21/04/2026" },
    { "npp": "NPP Mạnh Hà 1", "sl": 100, "ngay": "23/04/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 20, "ngay": "25/04/2026" },
    { "npp": "NPP Bảo Lâm", "sl": 100, "ngay": "6/5/2026" },
    { "npp": "NPP Vũ Tấm", "sl": 50, "ngay": "6/5/2026" },
    { "npp": "NPP Trung Nam", "sl": 60, "ngay": "7/5/2026" },
    { "npp": "NPP Hoa Việt", "sl": 50, "ngay": "7/5/2026" },
    { "npp": "NPP Long Châm", "sl": 30, "ngay": "8/5/2026" },
    { "npp": "NPP Nakoa", "sl": 15, "ngay": "8/5/2026" },
    { "npp": "NPP Minh Huy", "sl": 15, "ngay": "8/5/2026" },
    { "npp": "NPP Hiền Cường", "sl": 60, "ngay": "8/5/2026" },
    { "npp": "NPP Thắng Lợi", "sl": 100, "ngay": "9/5/2026" },
    { "npp": "NPP Thảo Thắng", "sl": 40, "ngay": "9/5/2026" },
    { "npp": "NPP Thanh Bình", "sl": 50, "ngay": "9/5/2026" },
    { "npp": "NPP Nhung Tùng", "sl": 100, "ngay": "9/5/2026" },
    { "npp": "NPP Bảo Cường", "sl": 30, "ngay": "9/5/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 50, "ngay": "11/5/2026" },
    { "npp": "NPP Hùng Huệ", "sl": 30, "ngay": "13/5/2026" },
    { "npp": "NPP Ngọc Kiên", "sl": 40, "ngay": "15/5/2026" },
    { "npp": "NPP Duy Anh", "sl": 50, "ngay": "15/5/2026" },
    { "npp": "NPP Đức Nam Tiến", "sl": 40, "ngay": "15/5/2026" },
    { "npp": "NPP Duy Khoa", "sl": 120, "ngay": "15/5/2026" },
    { "npp": "NPP Anh Minh HT", "sl": 50, "ngay": "15/5/2026" },
    { "npp": "NPP Phú Diễm", "sl": 80, "ngay": "16/5/2026" },
    { "npp": "NPP Tuấn Huyền", "sl": 30, "ngay": "18/5/2026" },
    { "npp": "NPP Thành Lụa", "sl": 20, "ngay": "19/5/2026" },
    { "npp": "NPP NAKOA", "sl": 80, "ngay": "19/5/2026" },
    { "npp": "NPP Trung Nam", "sl": 60, "ngay": "20/5/2026" },
    { "npp": "NPP Minh Huy", "sl": 80, "ngay": "22/5/2026" },
    { "npp": "NPP Tường Vy", "sl": 60, "ngay": "22/5/2026" },
    { "npp": "NPP Thanh Trà", "sl": 80, "ngay": "23/5/2026" },
    { "npp": "NPP Nam Khánh", "sl": 60, "ngay": "27/5/2026" },
    { "npp": "NPP Nakoa", "sl": 45, "ngay": "28/5/2026" },
    { "npp": "NPP Sơn Lâm", "sl": 50, "ngay": "28/5/2026" },
    { "npp": "NPP Tây Đô", "sl": 30, "ngay": "28/5/2026" },
    { "npp": "NPP HIền Thuận", "sl": 50, "ngay": "28/5/2026" },
    { "npp": "NPP Phương Đông", "sl": 100, "ngay": "30/5/2026" },
    { "npp": "NPP Thăng Hương", "sl": 100, "ngay": "2/6/2026" },
    { "npp": "NPP Tân Thúy", "sl": 100, "ngay": "2/6/2026" },
    { "npp": "NPP Gia Bảo", "sl": 100, "ngay": "2/6/2026" },
    { "npp": "NPP Long Châm", "sl": 30, "ngay": "3/6/2026" },
    { "npp": "NPP Thảo Nam", "sl": 25, "ngay": "5/6/2026" },
    { "npp": "NPP Cường Thịnh", "sl": 20, "ngay": "5/6/2026" },
    { "npp": "NPP Tình Dung", "sl": 100, "ngay": "6/6/2026" },
    { "npp": "NPP Phú Diễm", "sl": 100, "ngay": "8/6/2026" },
    { "npp": "NPP Tuấn Huyền", "sl": 30, "ngay": "9/6/2026" },
    { "npp": "NPP Dương Thiên Nhi", "sl": 50, "ngay": "9/6/2026" },

    { "npp": "NPP Long Liên", "sl": 100, "ngay": "9/6/2026" },
    { "npp": "NPP Sơn Lâm", "sl": 50, "ngay": "9/6/2026" },
    { "npp": "NPP HIền Thuận", "sl": 80, "ngay": "9/6/2026" }
];

// Dữ liệu kệ đã upload
const uploadedData = [
    { "npp": "NPP Anh Minh HT", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 286 },
    { "npp": "NPP Anh Viên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 4 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 300 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 33 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 2 },
    { "npp": "NPP Bảo Lâm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 206 },
    { "npp": "NPP Bảo Lâm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Công Giang", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 145 },
    { "npp": "NPP Công Giang", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Cường Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 249 },
    { "npp": "NPP Cường Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 8 },
    { "npp": "NPP Duy Anh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 276 },
    { "npp": "NPP Duy Anh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 5 },
    { "npp": "NPP Duy Khoa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 169 },
    { "npp": "NPP Dũng Béo", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 315 },
    { "npp": "NPP Dũng Béo", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Dũng Cúc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 17 },
    { "npp": "NPP Dương Minh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 335 },
    { "npp": "NPP Dương Minh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 11 },
    { "npp": "NPP Dương Minh", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 3 },
    { "npp": "NPP Hikoji", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 178 },
    { "npp": "NPP Hikoji", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Hikoji", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 1 },
    { "npp": "NPP Hiền Cường", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 97 },
    { "npp": "NPP Hoa Việt", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 183 },
    { "npp": "NPP Hoa Việt", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Hoàng Gia Bảo", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 1 },
    { "npp": "NPP Hoàng Minh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 312 },
    { "npp": "NPP Hoàng Minh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Hà Thanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 254 },
    { "npp": "NPP Hà Thanh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Hùng Huệ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 126 },
    { "npp": "NPP Hùng Huệ", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Hưng Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 298 },
    { "npp": "NPP Hưng Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Hải Hằng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 271 },
    { "npp": "NPP Hải Hằng", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Hồng Đức", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 49 },
    { "npp": "NPP Linh Trang", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 72 },
    { "npp": "NPP Linh Trang", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Long Châm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 170 },
    { "npp": "NPP Long Châm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Long Hải", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 169 },
    { "npp": "NPP Long Liên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 279 },
    { "npp": "NPP Long Liên", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Lâm Hạ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 127 },
    { "npp": "NPP Minh Châu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 114 },
    { "npp": "NPP Minh Châu", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Minh Huy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 1 },
    { "npp": "NPP Minh Lộc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 69 },
    { "npp": "NPP Mạnh Hà 1", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 322 },
    { "npp": "NPP Mạnh Hà 1", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Mạnh Hà 2", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 76 },
    { "npp": "NPP Mạnh Hà 2", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Nam Khánh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 6 },
    { "npp": "NPP Nguyên Vũ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 126 },
    { "npp": "NPP Nguyên Vũ", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 8 },
    { "npp": "NPP Nguyễn Đình Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 402 },
    { "npp": "NPP Ngọc Kiên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 219 },
    { "npp": "NPP Ngọc Kiên", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Ngọc Phúc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 311 },
    { "npp": "NPP Ngọc Phúc", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 8 },
    { "npp": "NPP Ngọc Thêu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 234 },
    { "npp": "NPP Ngọc Thêu", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Nhung Tùng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 285 },
    { "npp": "NPP Nhung Tùng", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Oanh Định", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 7 },
    { "npp": "NPP Phong Hiền", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 103 },
    { "npp": "NPP Phúc Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 204 },
    { "npp": "NPP Phúc Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Phương Hà", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 326 },
    { "npp": "NPP Phương Hà", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Phương Đông", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 509 },
    { "npp": "NPP Phương Đông", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 39 },
    { "npp": "NPP Phương Đông", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 1 },
    { "npp": "NPP Sơn Lâm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 172 },
    { "npp": "NPP Sơn Lâm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Thanh Bình", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 101 },
    { "npp": "NPP Thành Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 191 },
    { "npp": "NPP Thành Hân", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thành Lụa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 129 },
    { "npp": "NPP Thành Lụa", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thành Thanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 191 },
    { "npp": "NPP Thành Thanh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Thái Hoà", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 289 },
    { "npp": "NPP Thái Hoà", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Thông Thơm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 23 },
    { "npp": "NPP Thúy Diễm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 7 },
    { "npp": "NPP Thăng Hương", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 129 },
    { "npp": "NPP Thảo Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 255 },
    { "npp": "NPP Thảo Nam", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 8 },
    { "npp": "NPP Thảo Thắng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 172 },
    { "npp": "NPP Thảo Xuân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 30 },
    { "npp": "NPP Thắng Lợi", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 305 },
    { "npp": "NPP Thắng Lợi", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 7 },
    { "npp": "NPP Tiến Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 167 },
    { "npp": "NPP Trung Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 17 },
    { "npp": "NPP Trường Hằng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 117 },
    { "npp": "NPP Trường Hằng", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Tuấn Huyền", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 165 },
    { "npp": "NPP Tuấn Huyền", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Tuấn Huê", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 184 },
    { "npp": "NPP Tuấn Huê", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 24 },
    { "npp": "NPP Tuấn Huê", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 2 },
    { "npp": "NPP Tuấn Vân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 68 },
    { "npp": "NPP Tuấn Vân", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Tuấn Yến", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 177 },
    { "npp": "NPP Tuấn Yến", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 5 },
    { "npp": "NPP Tâm Bảo Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 9 },
    { "npp": "NPP Tân Bích An", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 47 },
    { "npp": "NPP Tân Hoa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 74 },
    { "npp": "NPP Tân Hoa", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Tân Thúy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 497 },
    { "npp": "NPP Tân Thúy", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 5 },
    { "npp": "NPP Tây Đô", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 239 },
    { "npp": "NPP Tây Đô", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 20 },
    { "npp": "NPP Tùng Phương", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 122 },
    { "npp": "NPP Tùng Phương", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Tường Vy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 5 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 479 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 41 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 2 },
    { "npp": "NPP Vũ Đức Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 129 },
    { "npp": "NPP Ánh Thu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 289 },
    { "npp": "NPP Ánh Thu", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Đồng Lợi", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 42 },
    { "npp": "NPP Đức Nam Tiến", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 181 },
    { "npp": "NPP Đức Oanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 94 }
];

const notUploadedData = [
    { "npp": "NPP Anh Minh HT", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 49 },
    { "npp": "NPP Anh Viên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 32 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 44 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Bảo Cường", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 1 },
    { "npp": "NPP Bảo Lâm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 130 },
    { "npp": "NPP Bảo Lâm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Công Giang", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 77 },
    { "npp": "NPP Cường Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 55 },
    { "npp": "NPP Cường Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Duy Anh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 11 },
    { "npp": "NPP Duy Khoa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 51 },
    { "npp": "NPP Dũng Béo", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 81 },
    { "npp": "NPP Dũng Cúc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 16 },
    { "npp": "NPP Dương Minh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 44 },
    { "npp": "NPP Dương Minh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Dương Thiên Nhi", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 25 },
    { "npp": "NPP Hikoji", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 72 },
    { "npp": "NPP Hikoji", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Hiền Cường", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 108 },
    { "npp": "NPP Hoa Việt", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 52 },
    { "npp": "NPP Hoàng Gia Bảo", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 16 },
    { "npp": "NPP Hoàng Minh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 27 },
    { "npp": "NPP Hà Thanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 25 },
    { "npp": "NPP Hà Thanh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Hùng Huệ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 41 },
    { "npp": "NPP Hùng Huệ", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Hưng Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 86 },
    { "npp": "NPP Hưng Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Hải Hằng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 7 },
    { "npp": "NPP Hồng Đức", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 48 },
    { "npp": "NPP Linh Trang", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 42 },
    { "npp": "NPP Long Châm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 42 },
    { "npp": "NPP Long Hải", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 24 },
    { "npp": "NPP Long Liên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 37 },
    { "npp": "NPP Lâm Hạ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 49 },
    { "npp": "NPP Minh Châu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 31 },
    { "npp": "NPP Minh Huy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 33 },
    { "npp": "NPP Minh Lộc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 13 },
    { "npp": "NPP Mạnh Hà 1", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 56 },
    { "npp": "NPP Mạnh Hà 1", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Mạnh Hà 2", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 15 },
    { "npp": "NPP Nam Khánh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 18 },
    { "npp": "NPP Nguyên Vũ", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 106 },
    { "npp": "NPP Nguyên Vũ", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Nguyễn Đình Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 30 },
    { "npp": "NPP Ngọc Kiên", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 53 },
    { "npp": "NPP Ngọc Phúc", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 29 },
    { "npp": "NPP Ngọc Thêu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 15 },
    { "npp": "NPP Nhung Tùng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 32 },
    { "npp": "NPP Oanh Định", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 34 },
    { "npp": "NPP Phong Hiền", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 59 },
    { "npp": "NPP Phúc Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 40 },
    { "npp": "NPP Phương Hà", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 22 },
    { "npp": "NPP Phương Đông", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 134 },
    { "npp": "NPP Phương Đông", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 6 },
    { "npp": "NPP Sơn Lâm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 81 },
    { "npp": "NPP Thanh Bình", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 93 },
    { "npp": "NPP Thành Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 55 },
    { "npp": "NPP Thành Hân", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thành Lụa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 60 },
    { "npp": "NPP Thành Thanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 26 },
    { "npp": "NPP Thái Hoà", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 47 },
    { "npp": "NPP Thông Thơm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 10 },
    { "npp": "NPP Thúy Diễm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 55 },
    { "npp": "NPP Thúy Diễm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thăng Hương", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 75 },
    { "npp": "NPP Thảo Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 47 },
    { "npp": "NPP Thảo Nam", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 4 },
    { "npp": "NPP Thảo Thắng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 143 },
    { "npp": "NPP Thảo Thắng", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thảo Xuân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 59 },
    { "npp": "NPP Thảo Xuân", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Thắng Lợi", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 53 },
    { "npp": "NPP Thắng Lợi", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Thắng Lợi", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 1 },
    { "npp": "NPP Tiến Thịnh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 139 },
    { "npp": "NPP Tiến Thịnh", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Trung Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 23 },
    { "npp": "NPP Trường Hằng", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 71 },
    { "npp": "NPP Trường Hằng", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Tuấn Huyền", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 36 },
    { "npp": "NPP Tuấn Huê", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 31 },
    { "npp": "NPP Tuấn Huê", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 3 },
    { "npp": "NPP Tuấn Vân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 95 },
    { "npp": "NPP Tuấn Yến", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 37 },
    { "npp": "NPP Tuấn Yến", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Tâm Bảo Hân", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 20 },
    { "npp": "NPP Tân Bích An", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 19 },
    { "npp": "NPP Tân Hoa", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 66 },
    { "npp": "NPP Tân Hoa", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 1 },
    { "npp": "NPP Tân Thúy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 37 },
    { "npp": "NPP Tây Đô", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 52 },
    { "npp": "NPP Tây Đô", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 2 },
    { "npp": "NPP Tây Đô", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 2 },
    { "npp": "NPP Tùng Phương", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 66 },
    { "npp": "NPP Tường Vy", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 10 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 145 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 2 (TB 02 kệ)", "so_lan": 7 },
    { "npp": "NPP Vũ Tấm", "muc_ke": "Mức 3 (TB 03 kệ)", "so_lan": 1 },
    { "npp": "NPP Vũ Đức Nam", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 18 },
    { "npp": "NPP Ánh Thu", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 81 },
    { "npp": "NPP Đồng Lợi", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 14 },
    { "npp": "NPP Đức Nam Tiến", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 61 },
    { "npp": "NPP Đức Oanh", "muc_ke": "Mức 1 (TB 01 kệ)", "so_lan": 123 }
]