// Dữ liệu NPP theo khu vực
const nppByKV = [
    ['NPP Bảo Lâm', 'KV1'],
    ['NPP Công Giang', 'KV1'],
    ['NPP Cường Thịnh', 'KV1'],
    ['NPP Đức Nam Tiến', 'KV1'],
    ['NPP Dũng Cúc', 'KV1'],
    ['NPP Lâm Hạ', 'KV1'],
    ['NPP Long Liên', 'KV1'],
    ['NPP Nguyên Vũ', 'KV1'],
    ['NPP Thảo Nam', 'KV1'],
    ['NPP Tuấn Huê', 'KV1'],
    ['NPP Tuấn Yến', 'KV1'],
    ['NPP Vũ Tấm', 'KV1'],
    
    ['NPP Duy Anh', 'KV2'],
    ['NPP Hoa Việt', 'KV2'],
    ['NPP Hùng Huệ', 'KV2'],
    ['NPP Long Châm', 'KV2'],
    ['NPP Ngọc Kiên', 'KV2'],
    ['NPP Ngọc Thêu', 'KV2'],
    ['NPP Phong Hiền', 'KV2'],
    ['NPP Phúc Thịnh', 'KV2'],
    ['NPP Phương Đông', 'KV2'],
    ['NPP Thành Lụa', 'KV2'],
    ['NPP Tuấn Huyền', 'KV2'],
    
    ['NPP Bảo Cường', 'KV3'],
    ['NPP Hikoji', 'KV3'],
    ['NPP Long Hải', 'KV3'],
    ['NPP Tân Hoa', 'KV3'],
    ['NPP Tây Đô', 'KV3'],
    ['NPP Thắng Lợi', 'KV3'],
    ['NPP Thành Hân', 'KV3'],
    ['NPP Tiến Thịnh', 'KV3'],
    
    ['NPP Ánh Thu', 'KV4'],
    ['NPP Đức Oanh', 'KV4'],
    ['NPP Dương Minh', 'KV4'],
    ['NPP Dũng Béo', 'KV4'],
    ['NPP Hưng Thịnh', 'KV4'],
    ['NPP Ngọc Phúc', 'KV4'],
    ['NPP Nguyễn Đình Hân', 'KV4'],
    ['NPP Tân Thúy', 'KV4'],
    ['NPP Thăng Hương', 'KV4'],
    ['NPP Thảo Thắng', 'KV4'],
    ['NPP Tùng Phương', 'KV4'],
    
    ['NPP Đồng Lợi', 'KV5'],
    ['NPP Hải Hằng', 'KV5'],
    ['NPP Hiền Cường', 'KV5'],
    ['NPP Hoàng Minh', 'KV5'],
    ['NPP Oanh Định', 'KV5'],
    ['NPP Sơn Lâm', 'KV5'],
    ['NPP Thái Hòa', 'KV5'],
    ['NPP Thảo Xuân', 'KV5'],
    ['NPP Tiên Lan', 'KV5'],
    ['NPP Duy Khoa', 'KV5'],
    ['NPP Tuấn Vân', 'KV5'],
    ['NPP Vũ Đức Nam', 'KV5'],
    
    ['NPP Anh Minh HT', 'KV6'],
    ['NPP Hà Thanh', 'KV6'],
    ['NPP Hồng Đức', 'KV6'],
    ['NPP Linh Trang', 'KV6'],
    ['NPP Mạnh Hà 1', 'KV6'],
    ['NPP Mạnh Hà 2', 'KV6'],
    ['NPP Minh Châu', 'KV6'],
    ['NPP Minh Lộc', 'KV6'],
    ['NPP Nhung Tùng', 'KV6'],
    ['NPP Phương Hà', 'KV6'],
    ['NPP Tân Bích An', 'KV6'],
    ['NPP Thanh Bình', 'KV6'],
    ['NPP Thành Thanh', 'KV6'],
    ['NPP Thông Thơm', 'KV6'],
    ['NPP Trường Hằng', 'KV6']
];

// Dữ liệu kệ đã xuất
const exportedData = [
 {   "npp": "NPP Vũ Tấm",   "sl": 319 },
 {   "npp": "NPP Dũng Cúc",   "sl": 36 },
 {   "npp": "NPP Công Giang",   "sl": 148 },
 {   "npp": "NPP Thảo Nam",   "sl": 175 },
 {   "npp": "NPP Tuấn Yến",   "sl": 176 },
 {   "npp": "NPP Bảo Lâm",   "sl": 281 },
 {   "npp": "NPP Nguyên Vũ",   "sl": 162 },
 {   "npp": "NPP Tuấn Huê",   "sl": 146 },
 {   "npp": "NPP Long Liên",   "sl": 191 },
 {   "npp": "NPP Cường Thịnh",   "sl": 87 },
 {   "npp": "NPP Đức Nam Tiến",   "sl": 137 },
 {   "npp": "NPP Lâm Hạ",   "sl": 142 },
 {   "npp": "NPP Thành Lụa",   "sl": 118 },
 {   "npp": "NPP Phương Đông",   "sl": 473 },
 {   "npp": "NPP Tuấn Huyền",   "sl": 155 },
 {   "npp": "NPP Hùng Huệ",   "sl": 156 },
 {   "npp": "NPP Ngọc Thêu",   "sl": 177 },
 {   "npp": "NPP Hoa Việt",   "sl": 128 },
 {   "npp": "NPP Phúc Thịnh",   "sl": 40 },
 {   "npp": "NPP Duy Anh",   "sl": 106 },
 {   "npp": "NPP Ngọc Kiên",   "sl": 132 },
 {   "npp": "NPP Phong Hiền",   "sl": 86 },
 {   "npp": "NPP Long Châm",   "sl": 132 },
 {   "npp": "NPP Thành Hân",   "sl": 256 },
 {   "npp": "NPP Long Hải",   "sl": 231 },
 {   "npp": "NPP Hikoji",   "sl": 160 },
 {   "npp": "NPP Bảo Cường",   "sl": 221 },
 {   "npp": "NPP Thắng Lợi",   "sl": 259 },
 {   "npp": "NPP Tân Hoa",   "sl": 177 },
 {   "npp": "NPP Tây Đô",   "sl": 155 },
 {   "npp": "NPP Tiến Thịnh",   "sl": 199 },
 {   "npp": "NPP Dương Minh",   "sl": 205 },
 {   "npp": "NPP Ánh Thu",   "sl": 251 },
 {   "npp": "NPP Đức Oanh",   "sl": 162 },
 {   "npp": "NPP Tùng Phương",   "sl": 104 },
 {   "npp": "NPP Thảo Thắng",   "sl": 211 },
 {   "npp": "NPP Hưng Thịnh",   "sl": 192 },
 {   "npp": "NPP Ngọc Phúc",   "sl": 161 },
 {   "npp": "NPP Nguyễn Đình Hân",   "sl": 196 },
 {   "npp": "NPP Tân Thúy",   "sl": 341 },
 {   "npp": "NPP Dũng Béo",   "sl": 354 },
 {   "npp": "NPP Thăng Hương",   "sl": 50 },
  {   "npp": "NPP Đồng Lợi",   "sl": 310 },
 {   "npp": "NPP Hoàng Minh",   "sl": 290 },
 {   "npp": "NPP Tuấn Vân",   "sl": 63 },
 {   "npp": "NPP Thái Hòa",   "sl": 191 },
 {   "npp": "NPP Tiên Lan",   "sl": 183 },
 {   "npp": "NPP Hiền Cường",   "sl": 141 },
 {   "npp": "NPP Oanh Định",   "sl": 51 },
 {   "npp": "NPP Thảo Xuân",   "sl": 71 },
 {   "npp": "NPP Vũ Đức Nam",   "sl": 17 },
 {   "npp": "NPP Hải Hằng",   "sl": 170 },
 {   "npp": "NPP Sơn Lâm",   "sl": 248 },
 {   "npp": "NPP Anh Minh HT",   "sl": 206 },
 {   "npp": "NPP Hồng Đức",   "sl": 64 },
 {   "npp": "NPP Minh Châu",   "sl": 202 },
 {   "npp": "NPP Mạnh Hà 1",   "sl": 332 },
 {   "npp": "NPP Mạnh Hà 2",   "sl": 71 },
 {   "npp": "NPP Nhung Tùng",   "sl": 335 },
 {   "npp": "NPP Thông Thơm",   "sl": 68 },
 {   "npp": "NPP Tân Bích An",   "sl": 47 },
 {   "npp": "NPP Linh Trang",   "sl": 230 },
 {   "npp": "NPP Minh Lộc",   "sl": 70 },
 {   "npp": "NPP Thanh Bình",   "sl": 61 },
 {   "npp": "NPP Thành Thanh",   "sl": 89 },
 {   "npp": "NPP Phương Hà",   "sl": 144 },
 {   "npp": "NPP Hà Thanh",   "sl": 146 },
 {   "npp": "NPP Trường Hằng",   "sl": 56 },
 {   "npp": "NPP Ánh Thu",   "sl": 100,   "ngay": "02/03/2026" },
 {   "npp": "NPP Thái Hòa",   "sl": 100,   "ngay": "02/03/2026" },
 {   "npp": "NPP Tân Thúy",   "sl": 200,   "ngay": "2/3/2026" },
 {   "npp": "NPP Tuấn Yến",   "sl": 150,   "ngay": "02/03/2026" },
 {   "npp": "NPP Tây Đô",   "sl": 70,   "ngay": "02/03/2026" },
 {   "npp": "NPP Thanh Bình",   "sl": 140,   "ngay": "3/3/2026" },
 {   "npp": "NPP Thành Lụa",   "sl": 40,   "ngay": "03/03/2026" },
 
 {   "npp": "NPP Đức Nam Tiến",   "sl": 120,   "ngay": "03/03/2026" },
 {   "npp": "NPP Tuấn Huê",   "sl": 100,   "ngay": "03/03/2026" },
 {   "npp": "NPP Oanh Định",   "sl": 150,   "ngay": "3/3/2026" },
 {   "npp": "NPP Bảo Cường",   "sl": 72,   "ngay": "03/03/2026" },
 {   "npp": "NPP Phúc Thịnh",   "sl": 100,   "ngay": "03/03/2026" },
 {   "npp": "NPP Hoàng Minh",   "sl": 100,   "ngay": "03/03/2026" },
 {   "npp": "NPP Hiền Cường",   "sl": 100,   "ngay": "4/3/2026" },
 {   "npp": "NPP Dương Minh",   "sl": 150,   "ngay": "6/3/2026" },
 {   "npp": "NPP Trường Hằng",   "sl": 120,   "ngay": "7/3/2026" },
 {   "npp": "NPP Hải Hằng",   "sl": 100,   "ngay": "09/03/2026" },
 {   "npp": "NPP Tiên Lan",   "sl": 180,   "ngay": "10/3/2026" },
 {   "npp": "NPP Nguyễn Đình Hân",   "sl": 50,   "ngay": "10/03/2026" },
 {   "npp": "NPP Dũng Béo",   "sl": 100,   "ngay": "11/03/2026" },
 {   "npp": "NPP Đức Oanh",   "sl": 150,   "ngay": "11/03/2026" },
 {   "npp": "NPP Thành Thanh",   "sl": 250,   "ngay": "11/3/2026" },
 {   "npp": "NPP Tuấn Huyền",   "sl": 50,   "ngay": "11/3/2026" },
 {   "npp": "NPP Thảo Thắng",   "sl": 100,   "ngay": "11/3/2026" },
 {   "npp": "NPP Thảo Xuân",   "sl": 75,   "ngay": "12/03/2026" },
 {   "npp": "NPP Vũ Đức Nam",   "sl": 50,   "ngay": "12/03/2026" },
 {   "npp": "NPP Hưng Thịnh",   "sl": 125,   "ngay": "12/3/2026" },
 {   "npp": "NPP Tuấn Vân",   "sl": 179,   "ngay": "12/03/2026" },
 {   "npp": "NPP Hùng Huệ",   "sl": 50,   "ngay": "12/3/2026" },
 {   "npp": "NPP Tân Hoa",   "sl": 80,   "ngay": "12/3/2026" },
 {   "npp": "NPP Cường Thịnh",   "sl": 100,   "ngay": "13/03/2026" },
 {   "npp": "NPP Thảo Nam",   "sl": 100,   "ngay": "13/03/2026" },
 {   "npp": "NPP Duy Anh",   "sl": 150,   "ngay": "14/03/2026" },
 {   "npp": "NPP Trường Hằng",   "sl": 120,   "ngay": "16/03/2026" },
 {   "npp": "NPP Ngọc Phúc",   "sl": 20,   "ngay": "16/03/2026" },
 {   "npp": "NPP Hà Thanh",   "sl": 200,   "ngay": "16/3/2026" },
 {   "npp": "NPP Minh Lộc",   "sl": 62,   "ngay": "16/3/2026" },
 {   "npp": "NPP Dũng Cúc",   "sl": 50,   "ngay": "18/03/2026" },
 {   "npp": "NPP Phương Hà",   "sl": 175,   "ngay": "19/03/2026" },
 {   "npp": "NPP Long Hải",   "sl": 50,   "ngay": "19/3/2026" },
 {   "npp": "NPP Nguyên Vũ",   "sl": 150,   "ngay": "20/03/2026" },
 {   "npp": "NPP Thái Hòa",   "sl": 50,   "ngay": "20/3/2026" },
 {   "npp": "NPP Hoa Việt",   "sl": 100,   "ngay": "20/3/2026" },
 {   "npp": "NPP Công Giang",   "sl": 120,   "ngay": "20/03/2026" },
 {   "npp": "NPP Tiến Thịnh",   "sl": 50,   "ngay": "20/03/2026" },
 {   "npp": "NPP Thành Hân",   "sl": 50,   "ngay": "21/03/2026" },
 {   "npp": "NPP Vũ Đức Nam",   "sl": 50,   "ngay": "21/3/2026" },
 {   "npp": "NPP Thảo Xuân",   "sl": 100,   "ngay": "21/03/2026" },
 {   "npp": "NPP Sơn Lâm",   "sl": 150,   "ngay": "21/3/2026" },
 {   "npp": "NPP Minh Lộc",   "sl": 38,   "ngay": "21/03/2026" },
 {   "npp": "NPP Ngọc Kiên",   "sl": 120,   "ngay": "21/03/2026" },
 {   "npp": " HT HT",   "sl": 50,   "ngay": "21/3/2026" },
 {   "npp": "NPP Thảo Nam",   "sl": 50,   "ngay": "22/3/2026" },
 {   "npp": "NPP Tân Hoa",   "sl": 60,   "ngay": "22/03/2026" },
 {   "npp": "NPP Nguyễn Đình Hân",   "sl": 100,   "ngay": "22/03/2026" },
 
 {   "npp": "NPP Vũ Tấm",   "sl": 100,   "ngay": "22/03/2026" },
 {   "npp": "NPP Hikoji",   "sl": 125,   "ngay": "22/03/2026" },
 {   "npp": "NPP Thăng Hương",   "sl": 200,   "ngay": "22/3/2026" },
 {   "npp": "NPP Ngọc Phúc",   "sl": 105,   "ngay": "22/03/2026" },
 {   "npp": "NPP Bảo Cường",   "sl": 28,   "ngay": "22/03/2026" },
 {   "npp": "NPP Tiến Thịnh",   "sl": 50,   "ngay": "22/03/2026" },
 {   "npp": "NPP Lâm Hạ",   "sl": 200,   "ngay": "22/03/2026" },
 {   "npp": "NPP Phúc Thịnh",   "sl": 50,   "ngay": "23/3/2026" },
 {   "npp": "NPP Phong Hiền",   "sl": 150,   "ngay": "23/03/2026" },
 {   "npp": "NPP Tuấn Huê",   "sl": 50,   "ngay": "23/03/2026" },
 {   "npp": "NPP Long Liên",   "sl": 50,   "ngay": "23/03/2026" },
 {   "npp": "NPP Tân Bích An",   "sl": 20,   "ngay": "24/03/2026" },
 {   "npp": "NPP Thông Thơm",   "sl": 50,   "ngay": "24/3/2026" },
 {   "npp": "NPP Hồng Đức",   "sl": 100,   "ngay": "24/03/2026" },
 {   "npp": "NPP Hồng Đức",   "sl": 80,   "ngay": "26/03/2026" },
 {   "npp": "NPP Long Liên",   "sl": 50,   "ngay": "27/03/2026" },
 {   "npp": "NPP Tuấn Huê",   "sl": 100,   "ngay": "27/03/2026" },
 {   "npp": "NPP Tân Hoa",   "sl": 10,   "ngay": "27/03/2026" },
 {   "npp": "NPP Thành Hân",   "sl": 50,   "ngay": "28/3/2026" },
 {   "npp": "NPP Mạnh Hà 2",   "sl": 50,   "ngay": "28/03/2026" },
 {   "npp": "NPP Anh Minh HT",   "sl": 70,   "ngay": "28/03/2026" },
 {   "npp": "NPP Thông Thơm",   "sl": 70,   "ngay": "31/03/2026" },
 {   "npp": "NPP Tùng Phương",   "sl": 50,   "ngay": "31/3/2026" },
 {   "npp": "NPP Mạnh Hà 2",   "sl": 50,   "ngay": "1/4/2026" },
 {   "npp": "NPP Phương Đông",   "sl": 100,   "ngay": "01/04/2026" },
 {   "npp": "NPP Tân Bích An",   "sl": 100,   "ngay": "06/04/2026" },
 {   "npp": "NPP Bảo Cường",   "sl": 50,   "ngay": "06/04/2026" },
{   "npp": "NPP Cường Thịnh",   "sl": 50,   "ngay": "07/04/2026" },
{   "npp": "NPP Phúc Thịnh",   "sl": 110,   "ngay": "10/04/2026" },
{   "npp": "NPP Tây Đô",   "sl": 50,   "ngay": "10/04/2026" },
{   "npp": "NPP Vũ Tấm",   "sl": 50,   "ngay": "11/04/2026" }
];

// Dữ liệu kệ đã upload
const uploadedData = [
 {   "npp": "NPP Anh Minh HT",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 158 },
 {   "npp": "NPP Bảo Cường",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 261 },
 {   "npp": "NPP Bảo Cường",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 26 },
 {   "npp": "NPP Bảo Cường",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Bảo Lâm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 251 },
 {   "npp": "NPP Bảo Lâm",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Công Giang",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 123 },
 {   "npp": "NPP Cường Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 174 },
 {   "npp": "NPP Cường Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Duy Anh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 182 },
 {   "npp": "NPP Duy Khoa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 89 },
 {   "npp": "NPP Dũng Béo",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 302 },
 {   "npp": "NPP Dũng Cúc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 23 },
 {   "npp": "NPP Dương Minh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 319 },
 {   "npp": "NPP Dương Minh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Dương Minh",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Hikoji",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 128 },
 {   "npp": "NPP Hikoji",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 6 },
 {   "npp": "NPP Hiền Cường",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 103 },
 {   "npp": "NPP Hoa Việt",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 144 },
 {   "npp": "NPP Hoàng Minh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 241 },
 {   "npp": "NPP Hoàng Minh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Hà Thanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 187 },
 {   "npp": "NPP Hà Thanh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Hà Thanh",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Hùng Huệ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 96 },
 {   "npp": "NPP Hùng Huệ",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 3 },
 {   "npp": "NPP Hưng Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 254 },
 {   "npp": "NPP Hưng Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 3 },
 {   "npp": "NPP Hải Hằng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 210 },
 {   "npp": "NPP Hồng Đức",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 66 },
 {   "npp": "NPP Linh Trang",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 54 },
 {   "npp": "NPP Long Châm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 134 },
 {   "npp": "NPP Long Châm",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Long Châm",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 7 },
 {   "npp": "NPP Long Hải",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 145 },
 {   "npp": "NPP Long Liên",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 206 },
 {   "npp": "NPP Long Liên",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Lâm Hạ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 122 },
 {   "npp": "NPP Minh Châu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 115 },
 {   "npp": "NPP Minh Lộc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 49 },
 {   "npp": "NPP Mạnh Hà 1",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 272 },
 {   "npp": "NPP Mạnh Hà 1",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 3 },
 {   "npp": "NPP Mạnh Hà 2",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 68 },
 {   "npp": "NPP Nguyên Vũ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 159 },
 {   "npp": "NPP Nguyên Vũ",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 5 },
 {   "npp": "NPP Nguyên Vũ",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Nguyễn Đình Hân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 256 },
 {   "npp": "NPP Ngọc Kiên",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 167 },
 {   "npp": "NPP Ngọc Phúc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 248 },
 {   "npp": "NPP Ngọc Phúc",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Ngọc Thêu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 160 },
 {   "npp": "NPP Nhung Tùng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 206 },
 {   "npp": "NPP Nhung Tùng",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Oanh Định",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 27 },
 {   "npp": "NPP Phong Hiền",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 80 },
 {   "npp": "NPP Phúc Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 156 },
 {   "npp": "NPP Phúc Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Phương Hà",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 197 },
 {   "npp": "NPP Phương Hà",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Phương Đông",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 385 },
 {   "npp": "NPP Phương Đông",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 22 },
 {   "npp": "NPP Sơn Lâm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 37 },
 {   "npp": "NPP Thanh Bình",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 117 },
 {   "npp": "NPP Thành Hân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 146 },
 {   "npp": "NPP Thành Hân",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Thành Lụa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 116 },
 {   "npp": "NPP Thành Lụa",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Thành Thanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 161 },
 {   "npp": "NPP Thành Thanh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Thái Hoà",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 199 },
 {   "npp": "NPP Thái Hoà",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Thông Thơm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 10 },
 {   "npp": "NPP Thảo Nam",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 241 },
 {   "npp": "NPP Thảo Nam",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 8 },
 {   "npp": "NPP Thảo Thắng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 199 },
 {   "npp": "NPP Thảo Thắng",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Thảo Xuân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 70 },
 {   "npp": "NPP Thắng Lợi",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 249 },
 {   "npp": "NPP Thắng Lợi",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 6 },
 {   "npp": "NPP Thắng Lợi",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tiến Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 167 },
 {   "npp": "NPP Tiến Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Trường Hằng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 91 },
 {   "npp": "NPP Tuấn Huyền",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 105 },
 {   "npp": "NPP Tuấn Huyền",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tuấn Huê",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 136 },
 {   "npp": "NPP Tuấn Huê",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 19 },
 {   "npp": "NPP Tuấn Huê",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 3 },
 {   "npp": "NPP Tuấn Vân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 72 },
 {   "npp": "NPP Tuấn Yến",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 141 },
 {   "npp": "NPP Tuấn Yến",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 6 },
 {   "npp": "NPP Tân Bích An",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 28 },
 {   "npp": "NPP Tân Hoa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 76 },
 {   "npp": "NPP Tân Hoa",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Tân Thúy",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 323 },
 {   "npp": "NPP Tây Đô",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 230 },
 {   "npp": "NPP Tây Đô",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 27 },
 {   "npp": "NPP Tây Đô",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tùng Phương",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 117 },
 {   "npp": "NPP Vũ Tấm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 511 },
 {   "npp": "NPP Vũ Tấm",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 22 },
 {   "npp": "NPP Vũ Tấm",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Vũ Đức Nam",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 104 },
 {   "npp": "NPP Ánh Thu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 261 },
 {   "npp": "NPP Đồng Lợi",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 28 },
 {   "npp": "NPP Đức Nam Tiến",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 179 },
 {   "npp": "NPP Đức Oanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 69 }
];

const notUploadedData = [
 {   "npp": "NPP Anh Minh HT",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 66 },
 {   "npp": "NPP Bảo Cường",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 31 },
 {   "npp": "NPP Bảo Cường",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 5 },
 {   "npp": "NPP Bảo Lâm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 63 },
 {   "npp": "NPP Công Giang",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 81 },
 {   "npp": "NPP Cường Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 43 },
 {   "npp": "NPP Duy Anh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 14 },
 {   "npp": "NPP Duy Khoa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 55 },
 {   "npp": "NPP Dũng Béo",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 67 },
 {   "npp": "NPP Dũng Cúc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 10 },
 {   "npp": "NPP Dương Minh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 29 },
 {   "npp": "NPP Hikoji",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 116 },
 {   "npp": "NPP Hiền Cường",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 77 },
 {   "npp": "NPP Hoa Việt",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 36 },
 {   "npp": "NPP Hoa Việt",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Hoàng Minh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 64 },
 {   "npp": "NPP Hà Thanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 7 },
 {   "npp": "NPP Hùng Huệ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 33 },
 {   "npp": "NPP Hùng Huệ",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 2 },
 {   "npp": "NPP Hưng Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 74 },
 {   "npp": "NPP Hưng Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Hải Hằng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 18 },
 {   "npp": "NPP Hồng Đức",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 11 },
 {   "npp": "NPP Linh Trang",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 50 },
 {   "npp": "NPP Linh Trang",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Long Châm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 19 },
 {   "npp": "NPP Long Châm",   "muc_ke": "Mức 3 (TB 03 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Long Hải",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 17 },
 {   "npp": "NPP Long Hải",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Long Liên",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 32 },
 {   "npp": "NPP Lâm Hạ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 16 },
 {   "npp": "NPP Minh Châu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 7 },
 {   "npp": "NPP Minh Lộc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 15 },
 {   "npp": "NPP Mạnh Hà 1",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 35 },
 {   "npp": "NPP Nguyên Vũ",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 53 },
 {   "npp": "NPP Nguyễn Đình Hân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 85 },
 {   "npp": "NPP Ngọc Kiên",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 17 },
 {   "npp": "NPP Ngọc Phúc",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 10 },
 {   "npp": "NPP Ngọc Phúc",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Ngọc Thêu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 15 },
 {   "npp": "NPP Nhung Tùng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 14 },
 {   "npp": "NPP Oanh Định",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 14 },
 {   "npp": "NPP Phong Hiền",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 34 },
 {   "npp": "NPP Phúc Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 11 },
 {   "npp": "NPP Phương Hà",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 41 },
 {   "npp": "NPP Phương Đông",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 110 },
 {   "npp": "NPP Phương Đông",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 4 },
 {   "npp": "NPP Sơn Lâm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 117 },
 {   "npp": "NPP Thanh Bình",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 19 },
 {   "npp": "NPP Thành Hân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 61 },
 {   "npp": "NPP Thành Hân",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Thành Lụa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 53 },
 {   "npp": "NPP Thành Thanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 13 },
 {   "npp": "NPP Thái Hoà",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 26 },
 {   "npp": "NPP Thông Thơm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 4 },
 {   "npp": "NPP Thăng Hương",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 48 },
 {   "npp": "NPP Thảo Nam",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 27 },
 {   "npp": "NPP Thảo Thắng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 90 },
 {   "npp": "NPP Thảo Xuân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 9 },
 {   "npp": "NPP Thảo Xuân",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Thắng Lợi",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 9 },
 {   "npp": "NPP Tiến Thịnh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 86 },
 {   "npp": "NPP Tiến Thịnh",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Trường Hằng",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 34 },
 {   "npp": "NPP Trường Hằng",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tuấn Huyền",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 25 },
 {   "npp": "NPP Tuấn Huê",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 30 },
 {   "npp": "NPP Tuấn Vân",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 28 },
 {   "npp": "NPP Tuấn Yến",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 39 },
 {   "npp": "NPP Tuấn Yến",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tân Bích An",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 11 },
 {   "npp": "NPP Tân Hoa",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 55 },
 {   "npp": "NPP Tân Hoa",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 3 },
 {   "npp": "NPP Tân Hoa;NPP Hoa Việt",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tân Thúy",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 107 },
 {   "npp": "NPP Tây Đô",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 22 },
 {   "npp": "NPP Tây Đô",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Tùng Phương",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 21 },
 {   "npp": "NPP Vũ Tấm",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 36 },
 {   "npp": "NPP Vũ Tấm",   "muc_ke": "Mức 2 (TB 02 kệ)",   "so_lan": 1 },
 {   "npp": "NPP Vũ Đức Nam",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 10 },
 {   "npp": "NPP Ánh Thu",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 25 },
 {   "npp": "NPP Đồng Lợi",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 18 },
 {   "npp": "NPP Đức Nam Tiến",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 45 },
 {   "npp": "NPP Đức Oanh",   "muc_ke": "Mức 1 (TB 01 kệ)",   "so_lan": 132 }
];